#!/usr/bin/env python3
#
#----------------
#### Read Me ####
#----------------
#
#
#
# To use, copy this script and plotting.py (found inside the ternary folder) to  
# the folder containing the input files (Note: Only requires those input files
# generated by write_params). The script takes two optional arguments of initial 
# conditions, phi1 and phi2. If supplied, the script will determine the composition
# of the two resulting phases and provide a tie line (this feature works well but
# could use some improvement). If ran without any command line arguments, it will
# produce a diagram with three generic tie lines. 
#
# Currently only the following cases of finite miscibility are fully operational/consistent:
#     polymer/nonsolvent
#     polymer/nonsolvent and solvent/nonsolvent
#
#
#
#----------------
#### Imports ####
#----------------

import numpy as np
import matplotlib.pylab as plt
import scipy.optimize as opt
from scipy.interpolate import interp1d
import sys
from plotting import *
import os
import json
import warnings
warnings.filterwarnings('ignore')
#--------------------------
#### Free Energy Class ####
#--------------------------

class FreeEnergy:

  def __init__(self, Nr, N1, N2, N3, Chi12, Chi13, Chi23, C_reg, delta):
    self.Nr = Nr
    self.N1 = N1
    self.N2 = N2
    self.N3 = N3
    self.Chi12 = Chi12
    self.Chi13 = Chi13
    self.Chi23 = Chi23
    self.C_reg = C_reg
    self.delta = delta

    self.alpha1 = N1/Nr
    self.alpha2 = N2/Nr
    self.alpha3 = N3/Nr
    self.ChiN12 = Chi12*Nr
    self.ChiN13 = Chi13*Nr
    self.ChiN23 = Chi23*Nr
    self.ChiN123 = self.ChiN12 - self.ChiN13 - self.ChiN23
    self.C_regN = C_reg*Nr

    self.bin_Chi_c = 0.5*(1./np.sqrt(N1) + 1./np.sqrt(N2))**2
    self.bin_phi_c = np.sqrt(N2)/(np.sqrt(N1)+np.sqrt(N2))
    self.bin_qdepth = self.Chi12/self.bin_Chi_c - 1.

  def F(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return phi1*np.log(phi1)/self.alpha1 + phi2*np.log(phi2)/self.alpha2 + phi3*np.log(phi3)/self.alpha3 + phi1*phi2*self.ChiN12 + phi1*phi3*self.ChiN13 + phi2*phi3*self.ChiN23 + self.C_regN*np.exp(-phi1/self.delta)

  # first derivatives
  def F1(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return (np.log(phi1)+1)/self.alpha1 - (np.log(phi3)+1)/self.alpha3 +             self.ChiN13*(1-2*phi1) + self.ChiN123*phi2             - self.C_regN/self.delta*np.exp(-phi1/self.delta) 

  def F2(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return (np.log(phi2)+1)/self.alpha2 - (np.log(phi3)+1)/self.alpha3 +             self.ChiN23*(1-2*phi2) + self.ChiN123*phi1

  # second derivatives
  def F11(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return 1./(self.alpha1*phi1) + 1./(self.alpha3*phi3) - 2*self.ChiN13 +             (self.C_regN/self.delta**2)*np.exp(-phi1/self.delta)

  def F12(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return 1./(self.alpha3*(phi3)) + self.ChiN123

  def F21(self, phi): return self.F12(phi)

  def F22(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return 1./(self.alpha2*phi2) + 1./(self.alpha3*phi3) - 2*self.ChiN23

  # third derivatives
  def F111(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return -1./(self.alpha1*(phi1)**2) + 1./(self.alpha3*(phi3)**2)             -(self.C_regN/self.delta**3)*np.exp(-phi1/self.delta)

  def F112(self, phi): 
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2 
    return 1./(self.alpha3*(phi3)**2)

  def F121(self, phi): return self.F112(phi)
  def F122(self, phi): return self.F112(phi)
  def F211(self, phi): return self.F112(phi)
  def F212(self, phi): return self.F112(phi)
  def F221(self, phi): return self.F112(phi)

  def F222(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return -1./(self.alpha2*(phi2)**2) + 1./(self.alpha3*(phi3)**2)

  # fourth derivatives
  def F1111(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return 2./(self.alpha1*(phi1)**3) + 2./(self.alpha3*(phi3)**3)             + (self.C_regN/self.delta**4)*np.exp(-phi1/self.delta)

  def F1121(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return 2./(self.alpha3*(phi3)**3)
    
  def F1221(self, phi): return self.F1121(phi)
  def F2221(self, phi): return self.F1121(phi)
  def F1112(self, phi): return self.F1121(phi)
  def F1122(self, phi): return self.F1121(phi)
  def F1222(self, phi): return self.F1121(phi)

  def F2222(self, phi):
    phi1 = phi[0]; phi2 = phi[1]; phi3 = 1-phi1-phi2
    return 2./(self.alpha2*(phi2)**3) + 2./(self.alpha3*(phi3)**3)

  # --- coexistence curve, spinodal, crit. pt ---

  def mu1(self, phi): 
    return self.alpha1*( (1-phi[0])*self.F1(phi) + ( -phi[1])*self.F2(phi) + self.F(phi) )
  def mu2(self, phi): 
    return self.alpha2*( ( -phi[0])*self.F1(phi) + (1-phi[1])*self.F2(phi) + self.F(phi) )
  def mu3(self, phi): 
    return self.alpha3*( ( -phi[0])*self.F1(phi) + ( -phi[1])*self.F2(phi) + self.F(phi) )

  # coexistence curve         
  def dF(self, phi, phi1_a):
    phi_a = np.array([phi1_a, phi[0]]); # phi1_a, phi2_a
    phi_b = np.array([phi[1], phi[2]]); # phi1_b, phi2_b
    return np.array([ (self.mu1(phi_a) - self.mu1(phi_b)),    (self.mu2(phi_a) - self.mu2(phi_b))*self.alpha1/self.alpha2,         (self.mu3(phi_a) - self.mu3(phi_b))*self.alpha1/self.alpha3 ])
  # spinodal curve
  def d2F(self, phi): return self.F11(phi)*self.F22(phi)-self.F12(phi)*self.F21(phi)

  # critical point curve
  def d3F(self, phi): 
    return self.F111(phi)*self.F22(phi)**2 - 3*self.F112(phi)*self.F12(phi)*self.F22(phi)            + 3*self.F122(phi)*self.F12(phi)**2 - self.F11(phi)*self.F12(phi)*self.F222(phi)

  def critical_point(self, phi): 
    return np.array([self.d2F(phi), self.d3F(phi)])
    
    
  def d2F_opt(self, phi):
    phi1, phi2 = phi
    phi3 = 1 - phi1 - phi2
    A1, A2, A3 = self.alpha1*phi1, self.alpha2*phi2, self.alpha3*phi3
    
    L = (A3 + A1 - 2*A1*A3*self.ChiN13 + A1*A3*self.C_regN / self.delta**2 * np.exp(-phi1 / self.delta))         * (A3 + A2 - 2 * A2 * A3 * self.ChiN23)
        
    R = A1 * A2 * (1 + A3*self.ChiN123)**2
    
    return L - R
  def d3F_opt(self, phi):
    phi1, phi2 = phi
    phi3 = 1 - phi1 - phi2
    A1, A2, A3 = self.alpha1*phi1, self.alpha2*phi2, self.alpha3*phi3
    B1, B2, B3 = self.alpha1*phi1**2, self.alpha2*phi2**2, self.alpha3*phi3**2
    
    delta = self.delta
    
    One = A1 * B2 * (B1 - B3 - B1*B3*self.C_regN/delta**3*np.exp(-phi1/delta))*(A3 + A2 - 2*A2*A3*self.ChiN23)**2
    Two = 3*A1*A2**2*B1*B2*(1 + A3*self.ChiN123)**2
    
    Three=A2**2*B1*(A3 + A1 - 2*A1*A3*self.ChiN13 + A1*A3*self.C_regN/delta**2 * np.exp(-phi1/delta))            *(1 + A3*self.ChiN123)*(B2-B3)
    Four= 3*A1*A2*B1*B2*(1 + A3*self.ChiN123)*(A3 + A2 - 2*A2*A3*self.ChiN23)
    
    return One + Two - Three - Four

  def critical_point_opt(self, phi):
        return np.array([self.d2F_opt(phi), self.d3F_opt(phi)])
        
  # --- two component free energies (polymer, non-solvent) ---
  def F_bin(self, phi, F, S): 
        
    if F > S:
        raise Exception("Please input parameters in numerically ascending order!")
    
    if F == 1 and S == 2: 
        alpha1, alpha2, Chi = self.alpha1, self.alpha2, self.ChiN12
        
    if F == 1 and S == 3:
        alpha1, alpha2, Chi = self.alpha1, self.alpha3, self.ChiN13
    
    if F == 2 and S == 3:
        alpha1, alpha2, Chi = self.alpha2, self.alpha3, self.ChiN23
        
    return phi*np.log(phi)/alpha1 + (1-phi)*np.log(1-phi)/alpha2 + Chi*phi*(1-phi) #+ self.C_regN*np.exp(-phi/self.delta)

  def F1_bin(self, phi, F, S):
    
    if F > S:
        raise Exception("Please input parameters in numerically ascending order!")
    
    if F == 1 and S == 2: 
        alpha1, alpha2, Chi = self.alpha1, self.alpha2, self.ChiN12
        
    if F == 1 and S == 3:
        alpha1, alpha2, Chi = self.alpha1, self.alpha3, self.ChiN13
    
    if F == 2 and S == 3:
        alpha1, alpha2, Chi = self.alpha2, self.alpha3, self.ChiN23
    
    return (np.log(phi)+1)/alpha1 - (np.log(1-phi)+1)/alpha2             + Chi*(1-2*phi) - self.C_regN/self.delta*np.exp(-phi/self.delta)

  def F11_bin(self, phi): 
    return 1./(self.alpha1*phi) + 1./(self.alpha2*(1-phi))       - 2.*self.ChiN12 + self.C_regN/self.delta**2*np.exp(-phi/self.delta)

  def F11_bin_opt(self, phi, F, S):
    if F > S:
        raise Exception("Please input parameters in numerically ascending order!")
    
    if F == 1 and S == 2: 
        alpha1, alpha2, Chi = self.alpha1, self.alpha2, self.ChiN12
        
    if F == 1 and S == 3:
        alpha1, alpha2, Chi = self.alpha1, self.alpha3, self.ChiN13
    
    if F == 2 and S == 3:
        alpha1, alpha2, Chi = self.alpha2, self.alpha3, self.ChiN23
    
    A1 = phi * alpha1
    A2 = (1-phi) * alpha2
    
    return A2 + A1 - 2*A1*A2*Chi + A1*A2*self.C_regN/self.delta**2*np.exp(-phi/self.delta)
    
  # binary phase coexistence calculation when phi3 = 0
  def binodal_bin(self, phi, F, S): 
    phi_a = phi[0]; phi_b = phi[1]
    d_phi = phi_a - phi_b
    nu_a = (self.bin_phi_c-phi_b)/d_phi
    nu_b = 1-nu_a
    F_bma = self.F_bin(phi_b, F, S) - self.F_bin(phi_a, F, S)
    dF_dphi_a = nu_a/d_phi*F_bma + nu_a*self.F1_bin(phi_a, F, S)
    dF_dphi_b = nu_b/d_phi*F_bma + nu_b*self.F1_bin(phi_b, F, S)
    return np.array([dF_dphi_a, dF_dphi_b])


  def binodal_bin_opt(self, phi, F, S):
        phi_a, phi_b = phi
        phi_c = self.bin_phi_c
        F_bma = self.F_bin(phi_b, F, S) - self.F_bin(phi_a, F, S)
        
        if F > S:
            raise Exception("Please input parameters in numerically ascending order!")
    
        if F == 1 and S == 2: 
            alpha1, alpha2, Chi = self.alpha1, self.alpha2, self.ChiN12

        if F == 1 and S == 3:
            alpha1, alpha2, Chi = self.alpha1, self.alpha3, self.ChiN13

        if F == 2 and S == 3:
            alpha1, alpha2, Chi = self.alpha2, self.alpha3, self.ChiN23

        A = alpha1 * phi_a * (phi_c - phi_b) * F_bma
        B = (phi_a - phi_b) * (phi_c-phi_b) * (1 - alpha1*phi_a/alpha2 - alpha1 / alpha2 * phi_a * np.log(1-phi_a) + alpha1 * phi_a * Chi * (1-2*phi_a))
        C = alpha1 * phi_b * (phi_a - phi_c) * F_bma
        D = ((phi_a - phi_b)**2 - (phi_a-phi_b)*(phi_c-phi_b)) * (1-alpha1*phi_b/alpha2 - alpha1/alpha2*phi_b*np.log(phi_b)                                                                  + alpha1 * phi_a * Chi * (1 - 2*phi_b))
        
        return np.array([A+B, C+D])


#------------------------
#### Extra Functions ####
#------------------------


def recBis(f, a, b, tol = 1e-10, numCall = 0, maxCall = 100, args = ()):
    if numCall >= maxCall:
        raise Exception("Maximum Recursion Reached on function recBis")
        return -1
    
    c = (a+b)/2
    
    if abs(f(c, *args)) < tol:
        return c  
    
    if f(c, *args)*f(a, *args) > 0:
        return recBis(f, c, b, numCall = numCall+1, args = args, tol = tol)
    
    else:
        return recBis(f, c, a, numCall = numCall+1, args = args, tol = tol)


def recBisStart(f, a, args = (), tol = 1e-10):
    s = np.linspace(a, 1-a, 100)

    for i in range(100):
        if f(a,*args)*f(s[i], *args) < 0:
            return recBis(f, s[i], a, tol = tol, args = args)
    
    return -1

def badComposition(phi_c, crit_pt_err):
    if np.any(phi_c < -1e-3):
        return True
    
    if np.any(phi_c > 1):
        return True
    
    if np.sum(phi_c)> 1+1e-2:
        return True

    if crit_pt_err > 1e-3:
        return True
    
    else:
        return False

def checkAccuracy(f, x, args = ()):
    return -np.log10(np.linalg.norm(f(x, *args)))


#----------------------------
#### Phase Diagram Class ####
#----------------------------

class PhaseDiagram: 
    def __init__(self, TFH, point = None):
        self.TFH = TFH
        self.PointBool = False
        if point != None:
            self.PointBool = True
            self.point = point
        print("\n\n") 
        print("----Evaluating Binary Systems----")
        self.binarySystemSpinodalAnalysis()
        self.printCase()
        print("\n\n----Solving For an Initial Critical Point----")
        self.critical()
        print("\n\n----Solving For the Spinodal Curve----")
        self.ternarySpinodalCurves()
        print("\n\n----Searching Spinodal Curve For Potential Critical Points----")
        self.critPostSpin()
        print("\n\n----Solving For the Binodal Curve----")
        self.binarySystemBinodalAnalysis()
        self.ternaryBinodalCurves()
        if self.PointBool:
            print("\n\n----Determining Phase Solution(s)----")
            self.PointAnalysis()
        print("\n\n----Plotting the Ternary Phase Diagram----")
        self.plotPhaseDiagram()
        print("\n\n")


#--------------------------------
####  Binary Case Evaluation ####
#--------------------------------

def binarySystemSpinodalAnalysis(self):
    TFH = self.TFH

    #Determine Finite Miscibility for Solvent/Non-solvent
    self.FM23 = True 
    NS_spinHigh = 1-recBisStart(TFH.F11_bin_opt, 0, args = (2,3), tol = 1e-10)
    NS_spinLow = 1-recBisStart(TFH.F11_bin_opt, 1, args = (2,3), tol = 1e-10)

    if NS_spinHigh - NS_spinLow < 1e-2:
        self.FM23 = False
    else:
        self.NS_spinHigh = NS_spinHigh
        self.NS_spinLow = NS_spinLow


    #Determine Finite Miscibility for Polymer/Non-solvent
    self.FM12 = True 
    PN_spinLow = recBisStart(TFH.F11_bin_opt, 0, args = (1,2), tol = 1e-10)
    PN_spinHigh = recBisStart(TFH.F11_bin_opt, 1, args = (1,2), tol = 1e-10)

    if PN_spinHigh - PN_spinLow < 1e-2:
        self.FM12 = False
    else:
        self.PN_spinHigh = PN_spinHigh
        self.PN_spinLow = PN_spinLow


    #Determine Finite Miscibility for Polymer/Solvent 
    self.FM13 = True  
    PS_spinLow = recBisStart(TFH.F11_bin_opt, 0, args = (1,3), tol = 1e-10)
    PS_spinHigh = recBisStart(TFH.F11_bin_opt, 1, args = (1,3), tol = 1e-10)

    if PS_spinHigh - PS_spinLow < 1e-2:
        self.FM13 = False
    else:
        self.PS_spinHigh = PS_spinHigh
        self.PS_spinLow = PS_spinLow

    self.s = np.sum([self.FM12, self.FM23, self.FM13])
    return

setattr(PhaseDiagram, "binarySystemSpinodalAnalysis", binarySystemSpinodalAnalysis)

def printCase(self):
    FM12 = self.FM12
    FM13 = self.FM13
    FM23 = self.FM23

    Title =     "Case 1: Finite Miscibility between Polymer and Non-solvent"
    if FM12 and not FM23 and not FM13:
        print(Title)

    Title =     "Case 2: Finite Miscibility between Solvent and Non-solvent"
    if not FM12 and FM23 and not FM13:
        print(Title)

    Title =     "Case 3: Finite Miscibility between Polymer and Solvent"
    if not FM12 and not FM23 and FM13:
        print(Title)

    Title =     "Case 4: Finite Miscibility between Polymer/Non-solvent and Solvent/Non-solvent"
    if FM12 and FM23 and not FM13:
        print(Title)

    Title =     "Case 5: Finite Miscibility between Polymer/Non-solvent and Polymer/Solvent"
    if FM12 and not FM23 and FM13:
        print(Title)

    Title =     "Case 6: Finite Miscibility between Solvent/Non-solvent and Polymer/Solvent"
    if not FM12 and FM23 and FM13:
        print(Title)

    Title =     "Case 7: Finite Miscibility between Solvent/Non-solvent and Polymer/Solvent and Polymer/Non-solvent"
    if FM12 and FM23 and FM13:
        print(Title)

    Title =     "Case 8: No Finite Miscibility"
    if not FM12 and not FM23 and not FM13:
        print(Title)

    return

setattr(PhaseDiagram, "printCase", printCase)

def binarySystemBinodalAnalysis(self):
    TFH = self.TFH
    if self.FM12:
        phia = np.linspace(self.PN_spinHigh, 1-1e-50, 100)
        phib = np.linspace(1e-50, self.PN_spinLow, 100)
        #print(phia,phib)
        phi_p = list()
        for i in range(100):
            for j in range(100):
                if np.linalg.norm(TFH.binodal_bin([phia[i], phib[j]], 1, 2)) < 7:
                    phi_t = [phia[i], phib[j]]
                    #print(phi_t)
                    phi_p.append(phi_t)
#                    if i==99 and j==99:
                        
        accuracy = 0
        ans = []
        for i in range(len(phi_p)):
            newAns = opt.fsolve(TFH.binodal_bin, [phi_p[i][0], phi_p[i][1]], args = (1,2))
            newAccuracy = checkAccuracy(TFH.binodal_bin, newAns, args = [1,2])
            # following three lines of code are for debugging
            #acc = np.zeros(9801)
            #acc[i]=accuracy
            #print(i)
            #np.savetxt('help.txt',acc)
            if accuracy < newAccuracy and newAns[0] > self.PN_spinHigh and newAns[1] < self.PN_spinLow:
                ans = newAns
                #print(ans,len(ans))
                #print(len(phi_p))
                accuracy = newAccuracy
        self.PN_binHigh, self.PN_binLow = ans
        print(ans,'for N=',N1)
        print(f"Polymer/Non-solvent Binodal Points {i}  {self.PN_binHigh:.4}   {self.PN_binLow:.4}")
        print(f"\tAccuracy: {checkAccuracy(TFH.binodal_bin, [self.PN_binHigh, self.PN_binLow], args = [1,2]):.4}")

    if self.FM23:
        phia = np.linspace(1e-18, 1-self.NS_spinHigh, 100)
        phib = np.linspace(1-self.NS_spinLow, 1-1e-18, 100)
        phi_p = list()
        for i in range(100):
            for j in range(100):
                if np.linalg.norm(TFH.binodal_bin([phia[i], phib[j]], 2, 3)) < .05:
                    phi_t = [phia[i], phib[j]]
                    phi_p.append(phi_t)

        phia = 0
        phib = 0

        for i in range(len(phi_p)):
            phia += phi_p[i][0]
            phib += phi_p[i][1]

        if len(phi_p) != 0:
            phia /= len(phi_p)
            phib /= len(phi_p)
        else:
            phia = (1-self.NS_spinHigh)/2
            phib = (1-self.NS_spinLow + 1)/2

        self.NS_binHigh, self.NS_binLow = 1 - opt.fsolve(TFH.binodal_bin, [phia, phib], args = (2, 3))
        print(f"Solvent/Non-solvent Binodal Points   {self.NS_binHigh:.4}   {self.NS_binLow:.4}")
        print(f"\tAccuracy: {checkAccuracy(TFH.binodal_bin, [self.NS_binHigh, self.NS_binLow], args = [2,3]):.4}")
        print(self.NS_binHigh)
    if self.FM13:
        phia = np.linspace(self.PS_spinHigh, 1-1e-18, 100)
        phib = np.linspace(1e-18, self.PS_spinLow, 100)
        phi_p = list()
        for i in range(100):
            for j in range(100):
                if np.linalg.norm(TFH.binodal_bin([phia[i], phib[j]], 1, 3)):
                    phi_t = [phia[i], phib[j]]
                    phi_p.append(phi_t)

        phia = 0
        phib = 0
        for i in range(len(phi_p)):
            phia += phi_p[i][0]
            phib += phi_p[i][1]

        if len(phi_p) != 0:
            phia /= len(phi_p)
            phib /= len(phi_p)
        else:
            phia = (self.PS_spinHigh + 1)/2
            phib = (self.PS_spinLow)/2


        self.PS_binHigh, self.PS_binLow = opt.fsolve(TFH.binodal_bin, [phia, phib], args = (1, 3))
        print(f"Polymer/Solvent Binodal Points   {self.PS_binHigh:.4}   {self.PS_binLow:.4}")

setattr(PhaseDiagram, "binarySystemBinodalAnalysis", binarySystemBinodalAnalysis)




#------------------------
#### Critical Points ####
#------------------------

def critical(self):
    TFH = self.TFH
    phi_guess = np.array([TFH.bin_phi_c, np.exp(-TFH.bin_qdepth)]);

    phi_c = opt.fsolve( TFH.critical_point, phi_guess, xtol=1e-10 )
    crit_pt_err = np.linalg.norm( TFH.critical_point(phi_c) )    

    if ( np.any(phi_c < 0) or np.any(phi_c > 1) or np.sum(phi_c)< 0. or np.sum(phi_c)> 1. ):
        print("\nATTENTION: Unable to find an appropriate guess value for critical point")
        phi_c = input("Please enter a guess value (e.g. .1,.6) or hit enter to use the default (.33,.33)")
        if phi_c == "":
            phi_c = np.array([1/3,1/3])
        else:
            phi_c = phi_c.split(",")
            first = float(phi_c[0])
            second= float(phi_c[1])
            phi_c = np.array([first, second])

    phi_c =opt.fsolve(TFH.critical_point_opt,  phi_c, xtol=1e-10)
    crit_pt_err = np.linalg.norm( TFH.critical_point_opt(phi_c) )
    BAD_CRIT = badComposition(phi_c, crit_pt_err)

    self.phi1_c = phi_c[0]
    self.phi2_c = phi_c[1]
    self.phi3_c = 1-phi_c[0] - phi_c[1]


    if BAD_CRIT:
        print("WARNING! Bad Critical Point Solution\n", phi_c, crit_pt_err)
    else:
        print(f"Critical Point {self.phi1_c:.4} {self.phi2_c:.4} {self.phi3_c:.4}\n\tAccuracy: {-np.log10(crit_pt_err):.4}")


# For Searching Spinodal Curves for Critical Points
def critPostSpin(self):
    TFH = self.TFH
    
    if self.s == 1:
        if checkAccuracy(TFH.critical_point_opt, [self.phi1_c, self.phi2_c])>10:
            self.phi_c1 = [self.phi1_c, self.phi2_c]
            print(f"Critical Point: {self.phi_c1[0]:.4} {self.phi_c1[1]:.4} {1-self.phi_c1[0]-self.phi_c1[1]:.4}                   \n\tAccuracy: {checkAccuracy(TFH.critical_point_opt, self.phi_c1):.4}")
            return
    
    if self.s > 0:
        phi = self.phi_s1

        phi_p = list()

        for i in range(100,len(phi)-100):
            if checkAccuracy(TFH.d3F_opt, phi[i, :-1]) > 4:
                phi_p.append(phi[i, :-1])
                
                
        
        if len(phi_p) > 0:
            phi_g = np.zeros(2)
            for i in range(len(phi_p)):
                phi_g += phi_p[i]
            phi_g /= len(phi_p)

        else:
            print("Method 2")
            phi_g = (phi[0,:-1] + phi[-1,:-1])/2

        self.phi_c1 = opt.fsolve(TFH.critical_point_opt, phi_g)
        crit_pt_err = np.linalg.norm(TFH.critical_point_opt(self.phi_c1))

        if badComposition(self.phi_c1, crit_pt_err):
            print("WARNING! Bad First Critical Point Solution\n", self.phi_c1, crit_pt_err, "\n")
        else:
            print(f"First Critical Point {self.phi_c1[0]:.4} {self.phi_c1[1]:.4} {1-self.phi_c1[0]-self.phi_c1[1]:.4}\n\tAccuracy: {-np.log10(crit_pt_err):.4}")
            print('true')

    if self.s > 1:
        phi = self.phi_s2

        phi_p = list()

        for i in range(100,len(phi)-100):
            if checkAccuracy(TFH.d3F_opt, phi[i, :-1]) > 4:
                phi_p.append(phi[i, :-1])

        if len(phi_p) > 0:
            phi_g = np.zeros(2)
            for i in range(len(phi_p)):
                phi_g += phi_p[i]
            phi_g /= len(phi_p)
            
        else:
            print("Method 2")
            phi_g = (phi[0,:-1] + phi[-1,:-1])/2

        self.phi_c2 = opt.fsolve(TFH.critical_point_opt,phi_g)
        crit_pt_err = np.linalg.norm(TFH.critical_point_opt(self.phi_c2))

        if badComposition(self.phi_c2, crit_pt_err):
            print("WARNING! Bad Second Critical Point Solution\n", self.phi_c2, crit_pt_err, "\n")
        else:
            print(f"Second Critical Point {self.phi_c2[0]:.4} {self.phi_c2[1]:.4} {1-self.phi_c2[0]-self.phi_c2[1]:.4}\n\tAccuracy: {-np.log10(crit_pt_err):.4}")


    if self.s > 2:
        phi = self.phi_s3

        phi_p = list()

        for i in range(100,len(phi)-100):
            if checkAccuracy(TFH.critical_point_opt, phi[i, :-1]) > 4:
                phi_p.append(phi[i, :-1])

        if len(phi_p) > 0:
            phi_g = np.zeros(2)
            for i in range(len(phi_p)):
                phi_g += phi_p[i]
            phi_g /= len(phi_p)
        else:
            print("Method 2")
            phi_g = phi[500,:-1]

        self.phi_c3 = opt.fsolve(TFH.critical_point_opt,phi_g)
        crit_pt_err = np.linalg.norm(TFH.critical_point_opt(self.phi_c3))

        if badComposition(self.phi_c3, crit_pt_err):
            print("WARNING! Bad Third Critical Point Solution\n", self.phi_c3, crit_pt_err, "\n")
        else:
            print(f"Third Critical Point {self.phi_c3[0]:.4} {self.phi_c3[1]:.4} {1-self.phi_c3[0]-self.phi_c3[1]:.4}\n\tAccuracy: {-np.log10(crit_pt_err):.4}")
            
setattr(PhaseDiagram, "critical", critical)
setattr(PhaseDiagram, "critPostSpin", critPostSpin)



#------------------------
#### Spinodal Curves ####
#------------------------

def ternarySpinodalCurves(self):
    FM12 = self.FM12
    FM13 = self.FM13
    FM23 = self.FM23

    
    if FM12 and not FM23 and not FM13:
        print(f"Polymer/Non-solvent Spinodal Points   {self.PN_spinLow:.4}   {self.PN_spinHigh:.4}")
        self.phi_s1 = self.Case1()

    if not FM12 and FM23 and not FM13:
        print(f"Solvent/Non-Solvent Spinodal Points   {self.NS_spinLow:.4}   {self.NS_spinHigh:.4}")
        self.phi_s1 = self.Case2()

    if not FM12 and not FM23 and FM13:
        print(f"Polymer/Solvent Spinodal Points   {self.PS_spinLow:.4}   {self.PS_spinHigh:.4}")
        self.phi_s1 = self.Case3()

    if FM12 and FM23 and not FM13:
        print(f"Polymer/Non-solvent Spinodal Points   {self.PN_spinLow:.4}   {self.PN_spinHigh:.4}")
        print(f"Solvent/Non-Solvent Spinodal Points   {self.NS_spinLow:.4}   {self.NS_spinHigh:.4}")
        self.phi_s1, self.phi_s2 = self.Case4()
        #self.phi_s1, self.phi_s2 = self.Case1(), self.Case2()

    if FM12 and not FM23 and FM13:
        print(f"Polymer/Non-solvent Spinodal Points   {self.PN_spinLow:.4}   {self.PN_spinHigh:.4}")
        print(f"Polymer/Solvent Spinodal Points       {self.PS_spinLow:.4}   {self.PS_spinHigh:.4}")
        self.phi_s1, self.phi_s2 = self.Case5()

    if not FM12 and FM23 and FM13:
        print(f"Solvent/Non-Solvent Spinodal Points   {self.NS_spinLow:.4}   {self.NS_spinHigh:.4}")
        print(f"Polymer/Solvent Spinodal Points       {self.PS_spinLow:.4}   {self.PS_spinHigh:.4}")
        self.phi_s1, self.phi_s2 = self.Case6()

    if FM12 and FM23 and FM13:
        print(f"Polymer/Non-solvent Spinodal Points   {self.PN_spinLow:.4}   {self.PN_spinHigh:.4}")
        print(f"Polymer/Solvent Spinodal Points       {self.PS_spinLow:.4}   {self.PS_spinHigh:.4}")
        print(f"Solvent/Non-Solvent Spinodal Points   {self.NS_spinLow:.4}   {self.NS_spinHigh:.4}")
        self.phi_s1, self.phi_s2, self.phi_s3 = self.Case7()
        #self.phi_s1, self.phi_s2, self.phi_s3 = self.Case7()


    return

setattr(PhaseDiagram, "ternarySpinodalCurves", ternarySpinodalCurves)

def Case1(self):
    TFH = self.TFH
    steps = 2000
    n = 0
    Printed = True
    
    if self.PN_spinLow > self.phi1_c:
        steps = int(steps/2)
        phi1_array = np.linspace(self.phi1_c+1e-3, self.PN_spinHigh, steps)
        phi2_array = np.zeros(steps)
        spinodal = lambda phi2, phi1: TFH.d2F_opt(([phi1, phi2]))

        phi_init = self.phi2_c

        for i in range(steps):
            phi_init = opt.fsolve(spinodal, phi_init, args = (phi1_array[i]))[0]
            phi2_array[i] = phi_init
            if checkAccuracy(spinodal, phi2_array[i], args = [phi1_array[i]]) < 4:
                print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
                n+=1
                Printed = True

        if Printed:
            print("\tNumber of Spinodal Points that did not converge:", n, "\n")
        
        phi_s1L = np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T
        
        phi3_array = np.linspace(1e-3, self.phi3_c, steps)
        phi1_array = np.zeros(steps)
        phi2_array = np.zeros(steps)
        spinodal = lambda phi1, phi3: TFH.d2F_opt(np.array([phi1, 1-phi1-phi3]))
        
        phi_init = self.PN_spinLow
        
        for i in range(steps):
            phi_init = opt.fsolve(spinodal, phi_init, args = (phi3_array[i]))[0]
            phi1_array[i] = phi_init
            phi2_array[i] = 1-phi_init-phi3_array[i]
        
        phi_s1R = np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T
        
        return np.vstack([phi_s1R, phi_s1L])
        
    else:
        phi1_array = np.linspace(self.PN_spinLow+1e-3, self.PN_spinHigh, steps)
        phi2_array = np.zeros(steps)
        spinodal = lambda phi2, phi1: TFH.d2F_opt(([phi1, phi2]))

        phi_init = self.phi2_c

        for i in range(steps):
            phi_init = opt.fsolve(spinodal, phi_init, args = (phi1_array[i]))[0]
            phi2_array[i] = phi_init

            if checkAccuracy(spinodal, phi2_array[i], args = [phi1_array[i]]) < 4:
                print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
                n+=1
                Printed = True

        if Printed:
            print("\tNumber of Spinodal Points that did not converge:", n, "\n")

        phi1_array = np.insert(phi1_array, 0, self.PN_spinLow)
        phi2_array = np.insert(phi2_array, 0, 1-self.PN_spinLow)
    return np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T  
    
def Case2(self):
    TFH = self.TFH
    steps = 2000
    n = 0
    Printed = False

    phi3_array = np.linspace(self.NS_spinLow+1e-5, self.NS_spinHigh, steps)
    phi1_array = np.zeros(steps)
    spinodal = lambda phi1, phi3: TFH.d2F_opt(np.array([phi1, 1-phi1-phi3]))

    phi_init = self.phi1_c

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi3_array[i]))[0]
        phi1_array[i] = phi_init
            
        if checkAccuracy(spinodal, phi1_array[i], args = [phi3_array[i]]) < 4:
            print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
            n+=1
            Printed = True
                
    if Printed:
        print("\tNumber of Spinodal Points that did not converge:", n, "\n")

    phi2_array = 1 - phi1_array - phi3_array

    phi1_array = np.insert(phi1_array, 0, 0)
    phi2_array = np.insert(phi2_array, 0, 1-self.NS_spinLow)

    return np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T 

def Case3(self):
    TFH = self.TFH
    steps = 1000
    n = 0
    Printed = False

    phi1_array = np.linspace(self.PS_spinLow+1e-5, self.PS_spinHigh, steps)
    phi2_array = np.zeros(steps)

    spinodal = lambda phi2, phi1: TFH.d2F_opt(np.array([phi1, phi2]))

    phi_init = self.phi2_c

    for i in range(steps):        
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi1_array[i]))[0]
        phi2_array[i] = phi_init
            
        if checkAccuracy(spinodal, phi_init, args = [phi1_array[i]]) < 4:
            print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
            n+=1
            Printed = True
                
    if Printed:
        print("\tNumber of Spinodal Points that did not converge:", n, "\n")

    phi1_array = np.insert(phi1_array, 0, self.PS_spinLow)
    phi2_array = np.insert(phi2_array, 0, 0)

    return np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T 
    
def Case4(self):
    TFH = self.TFH
    steps = 2000
    n = 0
    Printed = False

    phi1_array = np.linspace(1e-17, self.PN_spinLow, steps)
    phi2_array = np.zeros(steps)

    spinodal = lambda phi2, phi1: TFH.d2F_opt(([phi1, phi2]))
    phi_init = 1-self.NS_spinLow

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi1_array[i]))[0]
        phi2_array[i] = phi_init
            
        if checkAccuracy(spinodal, phi_init, args = [phi1_array[i]]) < 4:
            print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
            n+=1
            Printed = True

    phi_s1 = np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T


    phi3_array = np.linspace(1e-17, self.NS_spinHigh, steps)
    phi1_array = np.zeros(steps)

    spinodal = lambda phi1, phi3: TFH.d2F_opt(np.array([phi1, 1-phi1-phi3]))
    phi_init = self.PN_spinHigh

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi3_array[i]))[0]
        phi1_array[i] = phi_init
            
        if checkAccuracy(spinodal, phi_init, args = [phi3_array[i]]) < 4:
            print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
            n+=1
            Printed = True
                
    if Printed:
        print("\tNumber of Spinodal Points that did not converge:", n, "\n")

    phi2_array = 1 - phi1_array - phi3_array    
    phi_s2 = np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T
        
    return phi_s1, phi_s2
    
def Case5(self):
    TFH = self.TFH
    steps = 1000
    n = 0
    Printed = False

    phi2_array = np.linspace(1e-5, 1-self.PN_spinHigh, steps)
    phi1_array = np.zeros(steps)

    spinodal = lambda phi1, phi2: TFH.d2F_opt(np.array([phi1, phi2]))
    phi_init = self.PS_spinHigh

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi2_array[i]))[0]
        phi1_array[i] = phi_init
            
        if checkAccuracy(spinodal, phi_init, args = [phi2_array[i]]) < 4:
            print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
            n+=1
            Printed = True
                

    phi_s1 = np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T



    phi3_array = np.linspace(1e-5, 1-self.PS_spinLow, steps)
    phi1_array = np.zeros(steps)

    spinodal = lambda phi1, phi3: TFH.d2F_opt(np.array([phi1, 1-phi1-phi3]))
    phi_init = self.PN_spinLow

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi3_array[i]))[0]
        phi1_array[i] = phi_init    
        if checkAccuracy(spinodal, phi_init, args = [phi3_array[i]]) < 4:
            print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
            n+=1
            Printed = True
                
    if Printed:
        print("\tNumber of Spinodal Points that did not converge:", n, "\n")


    phi2_array = 1 - phi1_array - phi3_array    

    phi_s2 = np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T
        
    return phi_s1, phi_s2
    
def Case6(self):
    TFH = self.TFH
    steps = 1000
    n = 0
    Printed = False

    phi1_array = np.linspace(1e-5, self.PS_spinLow, steps)
    phi2_array = np.zeros(steps)

    spinodal = lambda phi2, phi1: TFH.d2F_opt(np.array([phi1, phi2]))
    phi_init = 1-self.NS_spinHigh

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi1_array[i]))[0]
        phi2_array[i] = phi_init
            
        if checkAccuracy(spinodal, phi_init, args = [phi1_array[i]]) < 4:
            print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
            n+=1
            Printed = True
                
    phi_s1 = np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T



    phi2_array = np.linspace(1e-5, 1-self.NS_spinLow, steps)
    phi1_array = np.zeros(steps)

    spinodal = lambda phi1, phi2: TFH.d2F_opt(np.array([phi1, phi2]))
    phi_init = self.PS_spinHigh

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi2_array[i]))[0]
        phi1_array[i] = phi_init
            
        
        if checkAccuracy(spinodal, phi_init, args = [phi2_array[i]]) < 4:
            print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "") 
            n+=1
            Printed = True
                
    if Printed:
        print("\tNumber of Spinodal Points that did not converge:", n, "\n")

    phi_s2 = np.vstack([phi1_array, phi2_array, 1-phi1_array-phi2_array]).T
        
    return phi_s1, phi_s2
 
def Case7(self):
    TFH = self.TFH
    steps = 1000
    Printed = False

    phi1_array = np.linspace(1e-17, self.PN_spinLow,steps)
    phi2_array = np.zeros(steps)

    spinodal = lambda phi2, phi1: TFH.d2F_opt([phi1,phi2])
    phi_init = 1-self.NS_spinLow

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi1_array[i]))
        phi2_array[i] = phi_init

        #if checkAccuracy(spinodal, phi_init, args = [phi1_array[i]]) < 4:
        #    print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end ="")
        #    n+=1
        #    Printed = True

        phi3_array = 1-phi1_array-phi2_array
        phi_s1 = np.vstack([phi1_array, phi2_array, phi3_array]).T

    phi2_array = np.linspace(1e-17,1-self.NS_spinHigh,steps)
    phi3_array = np.zeros(steps)

    spinodal = lambda phi3, phi2: TFH.d2F_opt([1-phi2-phi3, phi2])
    phi_init = 1-self.PS_spinLow#self.PN_spinHigh

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi2_array[i]))
        phi3_array[i] = phi_init

        phi1_array =1 - phi2_array - phi3_array
        phi_s2 = np.vstack([phi1_array, phi2_array, phi3_array]).T

    phi3_array = np.linspace(1e-17, 1-self.PS_spinHigh, steps)
    phi1_array = np.zeros(steps)

    spinodal = lambda phi1, phi3: TFH.d2F_opt([phi1, 1-phi1-phi3])
    phi_init = self.PN_spinHigh

    for i in range(steps):
        phi_init = opt.fsolve(spinodal, phi_init, args = (phi3_array[i]))
        phi1_array[i] = phi_init

        #if checkAccuracy(spinodal, phi_init, args = [phi3_array[i]]) < 4:
        #    print("\n**Warning: Spinodal May Be Inaccurate**\n" if not Printed else "", end = "")
        #    n+=1
        #    Printed = True

    if Printed:
        print("\tNumber of Spinodal Points that did not converge:", n, "\n")

    phi2_array = 1 - phi1_array - phi3_array
    phi_s3 = np.vstack([phi1_array, phi2_array, phi3_array]).T

    return phi_s1, phi_s2, phi_s3


setattr(PhaseDiagram, "Case1", Case1)
setattr(PhaseDiagram, "Case2", Case2)  
setattr(PhaseDiagram, "Case3", Case3)  
setattr(PhaseDiagram, "Case4", Case4)  
setattr(PhaseDiagram, "Case5", Case5)  
setattr(PhaseDiagram, "Case6", Case6)  
setattr(PhaseDiagram, "Case7", Case7)  



#-----------------------
#### Binodal Curves ####
#-----------------------

def ternaryBinodalCurves(self):
    TFH = self.TFH
    FM12 = self.FM12
    FM13 = self.FM13
    FM23 = self.FM23
    steps = 2000
    n = 0
    Printed = False
    if FM12 and not FM23 and not FM13:
        phi1a_arr = np.linspace(self.PN_binHigh, self.phi_c1[0]+1e-3, steps)
        #phi1a_arr = np.zeros(steps)
        phi2a_arr = np.zeros(steps)
        phi1b_arr = np.zeros(steps)
        phi2b_arr = np.zeros(steps)
        #binodal = lambda phi, phi3: TFH.dF(phi, 1-phi3-phi[0])
        binodal = lambda phi, phi1: TFH.dF(phi, phi1)
        #print(self.PN_binHigh,self.phi_c1[0],'switch')
        phi2a = 1-self.PN_binHigh
        phi1b = self.PN_binLow
        phi2b = 1-self.PN_binLow-1e-5
        for i in range(steps):
            phi2a, phi1b, phi2b = opt.fsolve(binodal, [phi2a, phi1b, phi2b], args = (phi1a_arr[i]))

            #phi1a_arr[i] = 1-phi2a-phi3a[i]
            phi2a_arr[i] = phi2a
            phi1b_arr[i] = phi1b
            phi2b_arr[i] = phi2b
            np.savetxt('phi3a.txt',1-phi1a_arr-phi2a_arr)
            if checkAccuracy(binodal, [phi2a,phi1b,phi2b], args = [phi1a_arr[i]]) < 4:
                print("\n**Warning: Binodal May Be Inaccurate**\n" if not Printed else "", end = "") 
                n+=1
                Printed = True
                
        if Printed:
            print("\tNumber of Binodal Points that did not converge:", n, "\n")
           
        self.phi_b1a = np.vstack([phi1a_arr, phi2a_arr, 1-phi1a_arr-phi2a_arr]).T
        self.phi_b1b = np.vstack([phi1b_arr, phi2b_arr, 1-phi1b_arr-phi2b_arr]).T

    if FM23 and not FM12 and not FM13:
         phi1a_arr = np.linspace(1.e-6,self.phi_c1[0]+1e-3,steps)
         # print(phi3b_arr)
         #phi3a_arr = np.linspace(1e-5,self.NS_binLow,steps)
         #phi3a_arr = np.zeros(steps)
         phi2a_arr = np.zeros(steps)
         phi1b_arr = np.zeros(steps)
         phi2b_arr = np.zeros(steps)
         #print(self.NS_binHigh,self.phi_c1[1],'norm')
         phi2a = self.NS_binHigh
         binodal = lambda phi, phi1: TFH.dF(phi,phi1) 
         phi3a = 1-self.NS_binHigh
         phi2b = self.NS_binLow
         phi3b = 1-self.NS_binLow-1e-5
         phi1b = 1-phi2b-phi3b
         for i in range(steps):
             phi2a, phi1b, phi2b = opt.fsolve(binodal,[phi2a, phi1b, phi2b], args = (phi1a_arr[i]))
             #phi3a_arr[i] = 1-phi1a_arr[i]-phi2a
             phi2a_arr[i] = phi2a
             phi1b_arr[i] = phi1b
             phi2b_arr[i] = phi2b
             #np.savetxt('phi2an.txt',phi2a_arr)
             if checkAccuracy(binodal,[phi3a, phi2b, phi3b], args = [phi2a_arr[i]]) < 4:
                 #r = checkAccuracy(binodal,[phi2b,phi2a,phi3a],args = [phi3b_arr[i]])
                 print('\n**Warning: Binodal May Be Inaccurate**\n' if not Printed else "", end = "")
                 n+=1
                 Printed = True
                 
         if Printed:
             print("\tNumber of Binodal Points that did not converge:", n, "\n")
        # for i in range (steps):
        #    if checkAccuracy(binodal,[phi2a,phi1b,phi2b],args = [phi3a_arr[i]])<4: 
         self.phi_b1a = np.vstack([phi1a_arr, phi2a_arr,1-phi1a_arr-phi2a_arr]).T
         self.phi_b1b = np.vstack([phi1b_arr, phi2b_arr,1-phi1b_arr-phi2b_arr]).T
 

    if FM12 and FM23 and not FM13:
        phi3a = np.linspace(1e-5, self.NS_binHigh-1e-5, steps)
        phi1a_arr = np.zeros(steps)
        phi2a_arr = np.zeros(steps)
        phi1b_arr = np.zeros(steps)
        phi2b_arr = np.zeros(steps)

        binodal = lambda phi, phi3: TFH.dF(phi, 1-phi3-phi[0])

        phi2a = 1-self.PN_binHigh-1e-5
        phi1b = self.PN_binLow-1e-5
        phi2b = 1-self.PN_binLow-1e-5
        
        for i in range(steps):
            phi2a, phi1b, phi2b = opt.fsolve(binodal, ([phi2a, phi1b, phi2b]), args = (phi3a[i]))
            phi1a_arr[i] = 1 - phi3a[i] - phi2a
            phi2a_arr[i] = phi2a
            phi1b_arr[i] = phi1b
            phi2b_arr[i] = phi2b
        
        
            if checkAccuracy(binodal, [phi2a,phi1b,phi2b], args = [phi3a[i]]) < 4:
                print("\n**Warning: Binodal May Be Inaccurate**\n" if not Printed else "", end = "") 
                n+=1
                Printed = True
                
        if Printed:
            print("\tNumber of Binodal Points that did not converge:", n, "\n")
        
        self.phi_b1a = np.vstack([phi1a_arr, phi2a_arr, phi3a]).T
        self.phi_b1b = np.vstack([phi1b_arr, phi2b_arr, 1-phi1b_arr-phi2b_arr]).T

    if FM12 and FM23 and FM13:
        phi1a_arr = np.linspace(self.PN_binHigh,1-1e-5,steps)
        print(phi1a_arr[0],phi1a_arr[steps-2],'hope')
        phi2a_arr = np.zeros(steps)
        phi1b_arr = np.zeros(steps)
        phi2b_arr = np.zeros(steps)

        binodal = lambda phi, phi1: TFH.dF(phi,phi1)

        phi2a =self.PN_binLow
        phi1b =self.PN_binLow
        phi2b =1-self.PN_binLow
 
        for i in range(steps):
              phi2a, phi1b, phi2b = opt.fsolve(binodal,[phi2a, phi1b, phi2b], args = (phi1a_arr[i]))
              #phi3a_arr[i] = 1-phi1a_arr[i]-phi2a
              phi2a_arr[i] = phi2a
              phi1b_arr[i] = phi1b
              phi2b_arr[i] = phi2b

#    self.phi_b1a = np.vstack([phi1a_arr, phi2a_arr,1-phi1a_arr-phi2a_arr]).T
#    self.phi_b1b = np.vstack([phi1b_arr, phi2b_arr,1-phi1b_arr-phi2b_arr]).T

        phi1a_arr2 = np.linspace(1e-17,self.PS_binLow/2,steps)
        phi2a_arr2 = np.zeros(steps)
        phi1b_arr2 = np.zeros(steps)
        phi2b_arr2 = np.zeros(steps)

        binodal = lambda phi, phi1: TFH.dF(phi,phi1)

        phi2a2 =1-self.NS_binHigh
        phi1b2 =self.PN_binLow
        phi2b2 =1-self.NS_binLow

        for i in range(steps):
              phi2a2, phi1b2, phi2b2 = opt.fsolve(binodal,[phi2a2, phi1b2, phi2b2], args = (phi1a_arr2[i]))
              #phi3a_arr[i] = 1-phi1a_arr[i]-phi2a
              phi2a_arr2[i] = phi2a2
              phi1b_arr2[i] = phi1b2
              phi2b_arr2[i] = phi2b2

        self.phi_b1a = np.vstack([phi1a_arr, phi2a_arr,1-phi1a_arr-phi2a_arr]).T
        self.phi_b1b = np.vstack([phi1b_arr, phi2b_arr,1-phi1b_arr-phi2b_arr]).T

        self.phi_b2a = np.vstack([phi1a_arr2, phi2a_arr2,1-phi1a_arr2-phi2a_arr2]).T
        self.phi_b2b = np.vstack([phi1b_arr2, phi2b_arr2,1-phi1b_arr2-phi2b_arr2]).T

setattr(PhaseDiagram, "ternaryBinodalCurves", ternaryBinodalCurves)



#----------------------------------
#### Phase Seperation Analysis ####
#----------------------------------

def PointAnalysis(self):
    phi1, phi2 = self.point
    phi3 = 1 - phi1 - phi2
    
    I_list = []
    
    for i in range(len(self.phi_b1a)):
        points = np.array([self.phi_b1a[i,:], self.phi_b1b[i,:]])
        if phi1 > points[0,0] or phi1 < points[1,0]:
            continue
        f = interp1d(points[:,0],points[:,1])
        g = interp1d(points[:,0],points[:,2])
        if f(phi1) - phi2 < 1e-3 and g(phi1) - phi3 < 1e-3:
            I_list.append(i)
    
    phi1a = 0
    phi2a = 0
    phi1b = 0
    phi2b = 0
    
    for i in I_list:
        phi1a += self.phi_b1a[i,0]
        phi2a += self.phi_b1a[i,1]
        phi1b += self.phi_b1b[i,0]
        phi2b += self.phi_b1b[i,1]
    
    phi1a /= len(I_list)
    phi2a /= len(I_list)
    phi1b /= len(I_list)
    phi2b /= len(I_list)
    
    print("Two Phase Region:")
    print(f"Polymer Phase:     {phi1a:.4}   {phi2a:.4}   {1-phi1a-phi2a:.4}")
    print(f"Nonsolvent Phase:  {phi1b:.4}   {phi2b:.4}   {1-phi1b-phi2b:.4}")
    self.tieLine = np.array([[phi1a,phi2a,1-phi1a-phi2a],[phi1b,phi2b,1-phi1b-phi2b]])
    return
    

setattr(PhaseDiagram, "PointAnalysis", PointAnalysis)

#-----------------
#### Plotting ####
#-----------------

def plotPhaseDiagram(self):
    plt.figure(frameon=False) #, figsize = (6, 7)
    ax=draw_boundary()
    ax.axis('off') # turn off outside axis and axis lines

    s = self.s

    if s > 0:    
        [xc1, yc1] = project([self.phi_c1[0], self.phi_c1[1], 1-self.phi_c1[0]-self.phi_c1[1]])
        #plt.plot(xc1, yc1, 'go', markersize=5, label = "Critical Points")
    if s > 1:    
        [xc2, yc2] = project([self.phi_c2[0], self.phi_c2[1], 1-self.phi_c2[0]-self.phi_c2[1]])
        #plt.plot(xc2, yc2, 'go', markersize=5)
    if s > 2:    
        [xc3, yc3] = project([self.phi_c3[0], self.phi_c3[1], 1-self.phi_c3[0]-self.phi_c3[1]])
        plt.plot(xc3, yc3, 'go', markersize=5)

    if s > 0: 
        [xs1, ys1] = project(self.phi_s1)
        plt.plot(xs1, ys1, 'r--', linewidth=2, label = "Spinodal") # spinodal
        
    if s > 1:    
        [xs2, ys2] = project(self.phi_s2)
        plt.plot(xs2, ys2, 'y--', linewidth=2)
        
    if s > 2:   
        [xs3, ys3] = project(self.phi_s3)
        plt.plot(xs3, ys3, 'g--', linewidth=2)
        
    if s > 0:  
        print(s,'s')
        [xb1a, yb1a] = project(self.phi_b1a)
        [xb1b, yb1b] = project(self.phi_b1b) 
        plt.plot(xb1a, yb1a, 'b-', linewidth=2, label = "Binodal")
        plt.plot(xb1b, yb1b, 'b-', linewidth=2)
       #np.savetxt('xs.txt',xb1a)
       #np.savetxt('new.txt',self.phi_b1a)


    if s > 1 and 'phi_b2a' in globals():
        print(s,'s')
        [xb2a, yb2a] = project(self.phi_b2a)
        [xb2b, yb2b] = project(self.phi_b2b)
        plt.plot(xb2a, yb2a, 'g-', linewidth=2, label = "Binodal")
        plt.plot(xb2b, yb2b, 'b-', linewidth=2)
    if self.PointBool:
        [tieX, tieY] = project(self.tieLine)
        plt.plot(tieX, tieY, 'b:', linewidth = 1.5)
        
        [pointX, pointY] = project([self.point[0], self.point[1], 1-self.point[0]-self.point[1]])
        plt.plot(pointX, pointY, color = "orange", marker = "s", linewidth = 7)

    else:
        
        [Low1, High1] = project([self.phi_b1a[250,:], self.phi_b1b[250,:]])
        [Low2, High2] = project([self.phi_b1a[1000,:], self.phi_b1b[1000,:]])
        [Low3, High3] = project([self.phi_b1a[1750,:], self.phi_b1b[1750,:]])

        plt.plot(Low1, High1, 'b:', linewidth=1.5, label = "Tie Lines")
        plt.plot(Low2, High2, 'b:', linewidth=1.5)
        plt.plot(Low3, High3, 'b:', linewidth=1.5)
    
        if 'phi_b2a' in globals():
            [Low1b, High1b] = project([self.phi_b2a[250,:], self.phi_b2b[250,:]])
            [Low2b, High2b] = project([self.phi_b2a[1000,:], self.phi_b2b[1000,:]])
            [Low3b, High3b] = project([self.phi_b2a[1750,:], self.phi_b2b[1750,:]])

            plt.plot(Low1b, High1b, 'r:', linewidth=1.5, label = "Tie Lines")
            plt.plot(Low2b, High2b, 'g:', linewidth=1.5)
            plt.plot(Low3b, High3b, 'b:', linewidth=1.5)

    plt.tight_layout(pad=-1)

    plt.savefig("PhaseDiagram.png", dpi = 300, transparent = False)
    return

setattr(PhaseDiagram, "plotPhaseDiagram", plotPhaseDiagram)



# -------------------------
#### Program Execution ####
# -------------------------

# set parameters
#FCfile = open('params_film_conc.in')
#FCjson = json.load(FCfile)
#flag = FCjson["FilmConcentrations"]


EMfile = open('params_EnergyModel.in')
EMjson = json.load(EMfile)
flag = EMjson["EnergyModelFlag"]
Nr = EMjson["Nr"]
C_reg = EMjson["C_reg"]
delta = EMjson["delta"]
N1 = EMjson["N"][0]
N2 = EMjson["N"][1]
N3 = EMjson["N"][2]
Chi12 = EMjson["Chi"][0][1]
Chi13 = EMjson["Chi"][0][2]
Chi23 = EMjson["Chi"][1][2]
grad0 = EMjson["Kappa"][0]
grad1 = EMjson["Kappa"][1]
# Calculations tend to be smoother while using a reference value of 1
Nr = 1 

TFH = FreeEnergy(Nr, N1, N2, N3, Chi12, Chi13, Chi23, C_reg, delta)

if len(sys.argv) > 1:
    PD = PhaseDiagram(TFH, [float(sys.argv[1]), float(sys.argv[2])])

else:
    PD = PhaseDiagram(TFH)
